Feat/web 3/splash section
QuantSoc/website pull request #12
Opened 2022-07-11 09:46 UTC by mck-jacky

finished implementation of Splash Section

2022-07-13 08:40 UTC, mck-jacky commented
finished implementation of Splash Section with new file structure

2022-07-13 10:24 UTC, imagine-hussain requested changes
There's a lot of small things here that could be a little differently (most of it is just convention stuff, the code is good) as you'll see in the comments on code but, overall, really well done!

I've just got a question about the `crop_logo_circle.png`. How was that generated?

 
==========
Img for my own reference
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/93496985/178709296-0371fbc6-fe65-4ed1-92d0-defe481ab4ee.png">

2022-07-13 10:24 UTC, imagine-hussain commented on src/routes/LandingPage/SplashSection/index.scss
> +.SplashButton {
https://stackoverflow.com/questions/11497094/remove-border-from-buttons

Removing that default border would really clean this up

2022-07-13 10:57 UTC, mck-jacky commented
> There's a lot of small things here that could be a little differently (most of it is just convention stuff, the code is good) as you'll see in the comments on code but, overall, really well done!
> 
> I've just got a question about the `crop_logo_circle.png`. How was that generated?
> 
> ========== Img for my own reference <img alt="image" width="1667" src="https://user-images.githubusercontent.com/93496985/178709296-0371fbc6-fe65-4ed1-92d0-defe481ab4ee.png">

I just downloaded the icon and cropped it by myself

2022-07-13 17:23 UTC, InvalidHero commented
It looks a bit off
- button styling can maybe be changed
- positioning seems a bit off, e.g. the button should maybe flex till the right side of the screen @imagine-hussain ?

2022-07-14 04:07 UTC, imagine-hussain commented
> It looks a bit off
> 
> - button styling can maybe changed
> 
> - positioning seems a bit off, e.g. the button should maybe flex till the right side of the screen @imagine-hussain ?

So the positioning is dependent on your screen width so it looks good sometimes and a bit off at other times. I'm happy to merge this as is though, and then leave the responsiveness to next sprint. But if @mck-jacky wants to address this, they Sgtm too.

The button styling I think looks off mainly cos of the default border that's still lingering around.
@InvalidHero

2022-07-17 13:20 UTC, imagine-hussain approved these changes

2022-07-17 13:30 UTC, mck-jacky commented
> > It looks a bit off
> > 
> > * button styling can maybe changed
> > * positioning seems a bit off, e.g. the button should maybe flex till the right side of the screen @imagine-hussain ?
> 
> So the positioning is dependent on your screen width so it looks good sometimes and a bit off at other times. I'm happy to merge this as is though, and then leave the responsiveness to next sprint. But if @mck-jacky wants to address this, they Sgtm too.
> 
> The button styling I think looks off mainly cos of the default border that's still lingering around. @InvalidHero

sorry got no time no fix it in the past few days. I will fix it in the next sprint

2022-07-17 13:35 UTC, merged